// src/components/Navigation.tsx
import React from 'react';
import { MessageSquareText } from 'lucide-react';

export const Navigation: React.FC = () => {
  return (
    <nav className="px-6 py-4">
      <div className="container mx-auto flex items-center justify-between">
        <div className="flex items-center space-x-2">
          <MessageSquareText className="h-6 w-6 text-indigo-600" />
          <span className="text-xl font-bold text-gray-900">TextMarley</span>
        </div>
      </div>
    </nav>
  );
};

// src/components/Navigation.vue
<template>
  <nav class="bg-white shadow-sm">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex justify-between h-16">
        <div class="flex items-center">
          <span class="text-2xl font-bold text-blue-600">TextMarley</span>
        </div>
        <div class="hidden sm:flex items-center space-x-8">
          <a href="#features" class="text-gray-600 hover:text-blue-600">Features</a>
          <a href="#pricing" class="text-gray-600 hover:text-blue-600">Pricing</a>
          <a href="#contact" class="text-gray-600 hover:text-blue-600">Contact</a>
          <button class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700">
            Get Started
          </button>
        </div>
      </div>
    </div>
  </nav>
</template>
